### ISSUE TITLE
Specify which AP's to expose to HomeKit

### ISSUE THREAD

**Issue by nielsth** [darnfish/homebridge-unifi-wap-light#1]
**Is your feature request related to a problem? Please describe:**
When enabling this plug-in, a light bulb for all UniFi devices that are adopted to the controller is added to HomeKit. This included switches etc. that are tucked away. I'd like to be able to block certain devices from being added to HomeKit, so only the AP's that are visible can be controlled.

**Describe the solution you'd like:**
Either an allowlist or blocklist to specify which AP's (of UniFi devices) are exposed to HomeKit.

**Describe alternatives you've considered:**
None.

**Additional context:**
In my case, 7 devices are added to HomeKit of which only 2 are AP's of which I would like to control the LED ring.

**Comment by darnfish** [comment]
This feature request makes sense :~) I'll try get it in ASAP!

**Comment by darnfish** [comment]
I've added `includeIds` and `excludeIds` to the plugin's config in `1.1.1`. You can figure out which which identifiers you need by viewing the logs during the Homebridge start process:
```
[2/18/2024, 4:25:31 PM] [UniFi WAP Lights] Restoring existing accessory from cache: Living Room (6414db676131ee25647ab962)
[2/18/2024, 4:25:31 PM] [UniFi WAP Lights] Restoring existing accessory from cache: Andrew’s Corridor (646dc6aff4544e0e40804c4e)
[2/18/2024, 4:25:31 PM] [UniFi WAP Lights] Restoring existing accessory from cache: Willine’s Bedroom (646dc828f4544e0e40804cbd)
```

Hope this helps!
